import type { Metadata } from "next";
import Header from '../components/Header'
import Hero from '../components/Hero';
import Footer from '../components/Footer';
import Skills from '../components/Skills';

import Script from "next/script";
import "./globals.css";
import './bootstrap.min.css'

export const metadata: Metadata = {
  title: "Rahul Singh",
  description: "Generated by Rahul Singh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://code.jquery.com/jquery-3.6.0.min.js" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></link>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" />
        <Script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"/>
      </head>
      <body>
        <Header />
        <Hero />
        <Skills/>
        <main className="flex-grow-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
